language: bash

services:
  - docker

script:
  - docker build --tag=app-generic-faker .
  - git clone https://github.com/keboola/ex-generic-mock-server.git ./server/
  - rmdir ./server/data/
  - git clone https://github.com/keboola/app-generic-faker-data.git ./server/data/
  - 

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
